defaults: &defaults
  working_directory: ~/turtl/desktop
  docker:
    - image: circleci/node:4.8.3

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: cache-v1-{{ .Branch }}-{{ checksum "package.json" }}-{{ checksum "../SHA256.core-rs" }}-{{ checksum "../SHA256.js"}}
      - run: git clone https://github.com/turtl/core-rs ../core-rs
      - run: git clone https://github.com/turtl/js ../js
      - run: npm install
      - run: make
      - run: find package.json data/app/ build/ | xargs sha256sum > BUILD.checksum
      - save_cache:
          key: cache-v1-{{ .Branch }}-{{ checksum "BUILD.checksum" }}
          paths:
            - data/app/
            - build/
            - node_modules

  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: cache-v1-{{ .Branch }}-{{ checksum "BUILD.checksum" }}
          key: cache-v1-{{ .Branch }}-
          key: cache-v1-

      - run:
          name: Run tests
          command: make test

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build

